### ISSUE TITLE
Cannot access the dataset and annotations via https://hdl.handle.net/11256/964

### ISSUE THREAD

**Issue by namng-uwu** [bdecost/uhcs-segment#4]
The uhcs segmentation dataset link is no longer accessible . Was it transferred to another location? Can you share the dataset?
<img width="532" alt="image" src="https://github.com/bdecost/uhcs-segment/assets/55870032/4816f9d6-303d-4f2e-a5dd-4ab56fff9f90">
Thank you!

**Comment by bdecost** [comment]
Hi, thanks for reporting this - the dataset is hosted on https://materialsdata.nist.gov, which is apparently currently under maintenance. I'll look into what the situation is with the data repository and the handle resolver

In the meantime there is a copy of the raw datafiles in this repository here: https://github.com/bdecost/uhcs-segment/tree/master/data

**Comment by namng-uwu** [comment]
Thanks Brian, much appreciated!
